## 9.1 NUMPY  #Saikiran Dasari  IBM (DV)

## ------------------------------------------------------------

Que) What is NUMPY?

NumPy is the fundamental package for scientific computing in Python. 
It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


# ---------------------------------------------------------

Que) Difference between numpy arrays and lists

•	There are several important differences between NumPy arrays and the standard Python sequences, NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically).

•	The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. 

•	 The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

•	NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.


## ----------------------------------------------------------------

CREATING NUMPY 1D ARRAY

A "numpy" array or "ndarray" is similar to a list. It's usually fixed in size and each element is of the same type, we can cast the list to numpy array by first importing the numpy. Or We can also quickly create the numpy array with arange function which creates an array within the range specified.

To verify the dimensionality of this array, use the shape property.

In example Since there is no value after the comma (20,) this is a one-dimensional array.


In [4]:
import numpy as np

#Casting a List to Numpy array
a = np.array([1,2,3,4])
print("Numpy array a = ", a)


Numpy array a =  [1 2 3 4]


In [6]:
a = np.arange(20)
print('Numpy array a = ', a)
# Since there is no value after the comma (20,) this is a one-dimensional array

Numpy array a =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [8]:
## To verify the dimensionality of this array, use the shape property.
## To check dimensionality of array use shape property
print(a.shape)

(20,)


### Accessing NUMPY 1D ARRAY

In [10]:
a = np.array([1,2,3,4,5,6])
print('Numpy array a = ', a)

#Accessing First Element of Numpy array
print('a[0] = ', a[0])

#Change the 2nd value of Numpy Array to 1000
a[1] = 1000
print('After changing 2nd value to 1000 = ', a)

#Slicing the 1st 3 values from Numpy Array
print('After Slicing = ', a[0:3])

Numpy array a =  [1 2 3 4 5 6]
a[0] =  1
After changing 2nd value to 1000 =  [   1 1000    3    4    5    6]
After Slicing =  [   1 1000    3]


Accessing and slicing operations for 1D array is same as list. Index values starts from 0 to length of the list.



### Creating Numpy 2D Array

If you only use the arrange function, it will output a one-dimensional array. To make it a two-dimensional array, chain its output with the reshape function.

In [12]:
a = np.arange(15)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
# In this example first, it will create the 15 integers.. 
## ..and then it will convert to two dimensional array with 3 rows and 5 columns.
a = np.arange(15).reshape(3,5)
print(a)
print('\n')
print("SHAPE of the Numpy Array is = ", a.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


SHAPE of the Numpy Array is =  (3, 5)


In [23]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Accessing NUMPY 2D Array

To access an element in a two-dimensional array, you need to specify an index for both the row and the column.

In [41]:
a = np.arange(15).reshape(3,5)
print(a)
print("\n")
print("Element in 1st Row and 1st Column = ", a[0,0])
print("Element in 2nd Row and 5th Column = ", a[1,4])
print("Element in 3rd Row and 5th Column = ", a[2,4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Element in 1st Row and 1st Column =  0
Element in 2nd Row and 5th Column =  9
Element in 3rd Row and 5th Column =  14
